// Generated by CoffeeScript 1.6.2
(function () {
  var query_absence;

  $(function () {
    $("#absence a[target='query']").click(function (e) {
      e.preventDefault();
      return query_absence();
    });
    $("#absence ul[target='semester-options'] a").click(function (e) {
      e.preventDefault();
      var selectedText = $(this).html();
      var selectedValue = $(this).attr("value");
      
      // 更新顯示文字和值
      $("#absence span[target='semester']").html(selectedText);
      $("#absence span[target='semester']").attr("value", selectedValue);
      
      // 更新按鈕的 aria-label
      var dropdownButton = $("#semester-dropdown-button");
      dropdownButton.attr("aria-label", "學期 " + selectedText + "，選單，輕觸兩下即可啟用");
      
      // 關閉 dropdown
      dropdownButton.dropdown('toggle');
      
      // 宣告選取結果
      $("#semester-announcement").text("已選取 " + selectedText);
      
      // 將焦點返回到按鈕
      setTimeout(function() {
        dropdownButton.focus();
        // 清除宣告文字,避免下次選取時重複
        setTimeout(function() {
          $("#semester-announcement").text("");
        }, 1000);
      }, 100);
      
      return false;
    });
    gadget.getContract("emba.student").send({
      service: "default.GetSemester",
      body: "",
      result: function (response, error, http) {
        var semester;
        var defaultSchoolYear = response.Result.SystemConfig.DefaultSchoolYear;

        // 設定學年度預設值
        var schoolYearInput = $("#absence input[target='schoolYear']");
        schoolYearInput.val(defaultSchoolYear);

        // 只有當有值時才更新 title 屬性
        if (defaultSchoolYear && defaultSchoolYear.toString().trim() !== '') {
          schoolYearInput.attr("title", "學年度，輕觸兩下即可啟用");
        } else {
          schoolYearInput.removeAttr("title");
        }
        
        semester = response.Result.SystemConfig.DefaultSemester;
        $("#absence span[target='semester']").attr("value", semester);
        var semesterText;
        if (semester === "0") {
          semesterText = "夏季學期";
        }
        if (semester === "1") {
          semesterText = "第 1 學期";
        }
        if (semester === "2") {
          semesterText = "第 2 學期";
        }
        $("#absence span[target='semester']").html(semesterText);
        
        // 更新按鈕的 aria-label 以包含預設學期
        $("#semester-dropdown-button").attr("aria-label", "學期 " + semesterText + "，選單，輕觸兩下即可啟用");
        
        // query_absence(); // 預設載入查詢結果
      }
    });
  });

  query_absence = function () {
    return gadget.getContract("emba.student").send({
      service: "default.GetAbsence",
      body: {
        Request: {
          SchoolYear: $("#absence input[target='schoolYear']").val(),
          Semester: $("#absence span[target='semester']").attr("value")
        }
      },
      result: function (response, error, http) {
        var cardItems = [];
        var tableItems = [];

        if (response.Result != null) {
          $(response.Result.Absence).each(function (index, item) {
            // 卡片式顯示資料
            cardItems.push(`
              <div class="dis-show">
                <div class="bd-callout px-2 pt-3 requiredt">
                  <div class="card text-muted cursor-pointer collapsed" aria-expanded="false" data-toggle="collapse" data-target="#classlist${index}" aria-controls="classlist${index}">
                    <button tabindex="0" id="class${index}" class="flex justify-center items-center w-full gap-x-2 pb-3" aria-describedby="sronly">
                        <span id="sronly" class="sr-only dis-none" aria-label="點擊展開或收合課程詳細資訊"></span>
                        <div class="flex flex-col text-left">
                          <div class="text-base font-semibold requiredt">${item.CourseName}</div>
                          <div class="whitespace-pre-line">${(item.StartTime.substr(0, 10))} ( ${(item.StartTime.substr(11, 5))} - ${(item.EndTime.substr(11, 5))} )</div>
                        </div>
                        <div class="flex-grow text-xl text-right pr-2">
                          <i class="collapse-close fa fa-angle-down font-bold text-xl" aria-hidden="true"></i>
                          <i class="collapse-open fa fa-angle-up font-bold text-xl" aria-hidden="true"></i>
                        </div>
                    </button>
                  </div>
                  <div class="text-muted -mx-4 px-4 collapse" style="background: rgb(250, 250, 250)" id="classlist${index}" aria-expanded="false">
                    <hr tabindex="-1" aria-hidden="true" class="mb-2 mt-0" />
                    <div class="flex justify-between mb-3">
                      <div tabindex="0" class="text-center" aria-label="課程識別碼 ${item.SubjectCode}">
                        <div aria-hidden="true">課程識別碼</div>
                        <div class="font-bold" aria-hidden="true">${item.SubjectCode}</div>
                      </div>
                      <div tabindex="0" class="text-center" aria-label="學年度 ${item.SchoolYear}">
                        <div aria-hidden="true">學年度</div>
                        <div class="font-bold" aria-hidden="true">${item.SchoolYear}</div>
                      </div>
                      <div tabindex="0" class="text-center" aria-label="學期 ${item.Semester === "0" ? "夏季學期" : "第" + item.Semester + "學期"}">
                        <div aria-hidden="true">學期</div>
                        <div class="font-bold" aria-hidden="true">${item.Semester === "0" ? "夏季學期" : "第" + item.Semester + "學期"}</div>
                      </div>
                    </div>
                    <hr tabindex="-1" aria-hidden="true" class="my-2" />
                    <div tabindex="0" class="text-center" aria-label="補課訊息 ${item.MakeUpDescription}">
                      <div aria-hidden="true">補課訊息</div>
                      <div aria-hidden="true" class="font-bold pb-2">${item.MakeUpDescription}</div>
                    </div>
                    </div>
                  </div>
                </div>
              </div>
            `);
            
            // 表格式顯示資料
            tableItems.push(`
              <tr>
                <td>${item.SchoolYear}</td>
                <td>${item.Semester === "0" ? "夏季學期" : "第" + item.Semester + "學期"}</td>
                <td>${item.CourseName}</td>
                <td>${item.SubjectCode}</td>
                <td>${(item.StartTime.substr(0, 10))}</td>
                <td>${(item.StartTime.substr(11, 5))} - ${(item.EndTime.substr(11, 5))}</td>
                <td>${item.MakeUpDescription}</td>
              </tr>
            `);
          });
        }
        
        // 更新查詢結果筆數顯示
        var resultCount = cardItems.length;
        var resultElement = $("#query-result-count");
        var resultText;
        
        if (resultCount > 0) {
          resultText = "查詢結果：共" + resultCount + "筆";
        } else {
          resultText = "查詢結果：無符合資料";
        }
        
        // 更新結果顯示並顯示元素
        resultElement.text(resultText).show();
        
        // 更新卡片容器內容（假設有一個專門的卡片容器）
        $("#absence #absence-cards").html((cardItems.length === 0 ? '' : cardItems.join("")));
        
        // 更新表格內容
        $("#absence #absence-detail tbody").html((tableItems.length === 0 ? '' : tableItems.join("")));
        
        // 無障礙：將焦點定位到結果區域並報讀結果
        setTimeout(function() {
          resultElement.focus();
        }, 100);
        
        return;
      }
    });
  };

}).call(this);
