// Generated by CoffeeScript 1.6.3
(function() {
  var getAttendance, getDiscipline, getMorality, global, myHandleArray, resetAttendance, resetData, resetDiscipline, resetMorality, resetSchoolYearSeme, set_error_message;

  global = {};

  jQuery(function() {
    gadget.autofit(document.getElementById("widget"));
    $("#behavior .btn-group").on("click", ".btn", function(e) {
      if (global.student != null) {
        global.behavior = {
          schoolYear: $(this).attr("school-year"),
          semester: $(this).attr("semester")
        };
        resetData();
        getMorality();
        getAttendance();
        return getDiscipline();
      }
    });
    $("#morality a[my-toggle=collapse]").click(function() {
      $("#morality-container").toggleClass("hide");
      $("#morality span[data-collapse] i").toggleClass("icon-chevron-up", $("#morality-container").is(".hide"));
      $("#morality span[data-collapse] i").toggleClass("icon-chevron-down", !$("#morality-container").is(".hide"));
      return false;
    });
    $("#attendance a[my-toggle=collapse]").click(function() {
      $("#attendance-container").toggleClass("hide");
      $("#attendance span[data-collapse] i").toggleClass("icon-chevron-up", $("#attendance-container").is(".hide"));
      $("#attendance span[data-collapse] i").toggleClass("icon-chevron-down", !$("#attendance-container").is(".hide"));
      return false;
    });
    $("#discipline a[my-toggle=collapse]").click(function() {
      $("#discipline-container").toggleClass("hide");
      $("#discipline span[data-collapse] i").toggleClass("icon-chevron-up", $("#discipline-container").is(".hide"));
      $("#discipline span[data-collapse] i").toggleClass("icon-chevron-down", !$("#discipline-container").is(".hide"));
      return false;
    });
    return gadget.getContract("ischool.AD.student").send({
      service: "_.GetCurrentSemester",
      body: "",
      result: function(response, error, xhr) {
        if (error != null) {
          return set_error_message('#mainMsg', 'GetCurrentSemester', error);
        } else {
          global.schoolYear = response.Current.SchoolYear;
          global.semester = response.Current.Semester;
          return gadget.getContract("ischool.AD.student").send({
            service: "_.GetStudentInfo",
            body: "",
            result: function(response, error, xhr) {
              var _ref;
              if (error != null) {
                return set_error_message('#mainMsg', 'GetStudentInfo', error);
              } else {
                if (((_ref = response.Result) != null ? _ref.Student : void 0) != null) {
                  resetData();
                  global.students = $(response.Result.Student);
                  return global.students.each(function(index, student) {
                    if (index === 0) {
                      global.student = student;
                      global.behavior = {
                        schoolYear: global.schoolYear,
                        semester: global.semester
                      };
                      resetSchoolYearSeme();
                      resetData();
                      getDiscipline();
                      /* 下載上課時間表*/

                      gadget.getContract("ischool.AD.student").send({
                        service: "_.GetPeriodMappingTable",
                        body: "",
                        result: function(response, error, xhr) {
                          var _ref1;
                          if (error != null) {
                            return set_error_message('#mainMsg', 'GetPeriodMappingTable', error);
                          } else {
                            global.periods = [];
                            global.period_type = {};
                            global.absence = {};
                            if (((_ref1 = response.Response) != null ? _ref1.Period : void 0) != null) {
                              $(response.Response.Period).each(function(index, item) {
                                global.periods.push(item);
                                if (!global.period_type[item.Type]) {
                                  return global.period_type[item.Type] = 0;
                                }
                              });
                              /* 下載缺曠類別表*/

                              return gadget.getContract("ischool.AD.student").send({
                                service: "_.GetAbsenceMappingTable",
                                body: "",
                                result: function(response, error, xhr) {
                                  var _ref2;
                                  if (error != null) {
                                    return set_error_message('#mainMsg', 'GetAbsenceMappingTable', error);
                                  } else {
                                    if (((_ref2 = response.Response) != null ? _ref2.Absence : void 0) != null) {
                                      $(response.Response.Absence).each(function(index, item) {
                                        return global.absence[item.Name] = item.Abbreviation;
                                      });
                                      return getAttendance();
                                    }
                                  }
                                }
                              });
                            }
                          }
                        }
                      });
                      return gadget.getContract("ischool.AD.student").send({
                        service: "_.GetMorality",
                        body: "",
                        result: function(response, error, xhr) {
                          if (error != null) {
                            return set_error_message('#mainMsg', 'GetMorality', error);
                          } else {
                            global.morality = response;
                            return getMorality();
                          }
                        }
                      });
                    }
                  });
                }
              }
            }
          });
        }
      }
    });
  });

  myHandleArray = function(obj) {
    var result;
    if (!$.isArray(obj)) {
      result = [];
      if (obj) {
        result.push(obj);
      }
    } else {
      result = obj;
    }
    return result;
  };

  resetSchoolYearSeme = function() {
    var items, student, _ref;
    student = global.student;
    items = [];
    items.push("<button class='rounded-lg p-4 text-xl text-primary font-semibold bg-base-100 btn active' school-year='" + global.schoolYear + "' semester='" + global.semester + "'>" + (global.schoolYear + '' + global.semester) + "</button>");
    if (((_ref = student.SemsHistory) != null ? _ref.History : void 0) != null) {
      student.SemsHistory.History = myHandleArray(student.SemsHistory.History);
      $(student.SemsHistory.History.sort($.by("desc", "SchoolYear", $.by("desc", "Semester")))).each(function(index, item) {
        if (!(this.SchoolYear === global.schoolYear && this.Semester === global.semester)) {
          return items.push("<button class='rounded-lg p-4 text-xl text-primary font-semibold bg-base-100 btn' school-year='" + this.SchoolYear + "' semester='" + this.Semester + "'>" + (this.SchoolYear + '' + this.Semester) + "</button>");
        }
      });
    }
    return $("#behavior .btn-group").html(items.join(""));
  };

  resetData = function() {
    $("#morality-container").removeClass("hide").html("");
    $("#morality span[data-collapse] i").addClass("icon-chevron-down").removeClass("icon-chevron-up");
    $("#morality-view").addClass("hide");
    $("#attendance h2 span").html("");
    $("#attendance .my-thumbnails").html("");
    $("#attendance-container").addClass("hide").html("");
    $("#attendance span[data-collapse] i").addClass("icon-chevron-up").removeClass("icon-chevron-down");
    $("#attendance-view").addClass("hide");
    $("#discipline .my-thumbnails").addClass("hide");
    $("#discipline-container").addClass("hide").html("");
    $("#discipline span[data-collapse] i").addClass("icon-chevron-up").removeClass("icon-chevron-down");
    $("#discipline-view").addClass("hide");
    $("#merit-a").html("<span class=''>0</span>");
    $("#merit-b").html("<span class=''>0</span>");
    $("#merit-c").html("<span class=''>0</span>");
    $("#demerit-a").html("<span class=''>0</span>");
    $("#demerit-b").html("<span class=''>0</span>");
    $("#demerit-c").html("<span class=''>0</span>");
    return $("#demerit-d").html("");
  };

  resetMorality = function() {
    $("#morality-container").removeClass("hide").html("");
    $("#morality span[data-collapse] i").addClass("icon-chevron-down").removeClass("icon-chevron-up");
    return $("#morality-view").addClass("hide");
  };

  resetAttendance = function() {
    $("#attendance h2 span").html("");
    $("#attendance .my-thumbnails").html("");
    $("#attendance-container").addClass("hide").html("");
    $("#attendance span[data-collapse] i").addClass("icon-chevron-up").removeClass("icon-chevron-down");
    return $("#attendance-view").addClass("hide");
  };

  resetDiscipline = function() {
    $("#discipline .my-thumbnails").addClass("hide");
    $("#discipline-container").addClass("hide").html("");
    $("#discipline span[data-collapse] i").addClass("icon-chevron-up").removeClass("icon-chevron-down");
    $("#discipline-view").addClass("hide");
    $("#merit-a").html("<span class=''>0</span>");
    $("#merit-b").html("<span class=''>0</span>");
    $("#merit-c").html("<span class=''>0</span>");
    $("#demerit-a").html("<span class=''>0</span>");
    $("#demerit-b").html("<span class=''>0</span>");
    $("#demerit-c").html("<span class=''>0</span>");
    return $("#demerit-d").html("");
  };

  getMorality = function() {
    var my_schoolYear, my_semester;
    my_schoolYear = global.behavior.schoolYear;
    my_semester = global.behavior.semester;
    return gadget.getContract("ischool.AD.student").send({
      service: "_.GetMoralScore",
      body: "<Request>\n  <StudentID>" + global.student.StudentID + "</StudentID>\n  <SchoolYear>" + global.behavior.schoolYear + "</SchoolYear>\n  <Semester>" + global.behavior.semester + "</Semester>\n</Request>",
      result: function(response, error, xhr) {
        var btn_active, items, _ref, _ref1;
        btn_active = $('.my-schoolyear-semester-widget button.active');
        if (btn_active.attr("school-year") === global.behavior.schoolYear && btn_active.attr("semester") === global.behavior.semester) {
          resetMorality();
          if (error != null) {
            return set_error_message('#mainMsg', 'GetMoralScore', error);
          } else {
            items = [];
            if (((_ref = response.Result) != null ? _ref.SbComment : void 0) != null) {
              items.push("<div class='mt-3'>\n  <div class='font-semibold'>導師評語</div>\n  <div>" + (this.response.Result.SbComment || '') + "</div>\n</div>");
            }
            if (((_ref1 = global.morality.Response) != null ? _ref1.Morality : void 0) != null) {
              $(global.morality.Response.Morality).each(function() {
                var morality, that, tmpFace, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7;
                items.push("<div class='mt-3'>\n  <div class='font-semibold'>" + (this.Face || '') + "</div>");
                that = this;
                tmpFace = '';
                if (((_ref2 = response.Result) != null ? (_ref3 = _ref2.DailyLifeScore) != null ? (_ref4 = _ref3.Content) != null ? _ref4.Morality : void 0 : void 0 : void 0) != null) {
                  morality = response.Result.DailyLifeScore.Content.Morality;
                }
                if (((_ref5 = response.Result) != null ? (_ref6 = _ref5.DailyLifeScore) != null ? (_ref7 = _ref6.TextScore) != null ? _ref7.Morality : void 0 : void 0 : void 0) != null) {
                  morality = response.Result.DailyLifeScore.TextScore.Morality;
                }
                if (morality) {
                  $(morality).each(function() {
                    if (this.Face === that.Face) {
                      tmpFace = this['@text'];
                      return false;
                    }
                  });
                }
                return items.push("<div>" + (tmpFace || '') + "</div>\n</div>");
              });
              $("#morality-view").removeClass("hide");
              return $("#morality-container").html("<div class='text-base space-y-3'>\n" + (items.join("")) + "\n</div>");
            } else {
              return $("#morality-container").html("目前無資料");
            }
          }
        }
      }
    });
  };

  getAttendance = function() {
    var my_schoolYear, my_semester;
    my_schoolYear = global.behavior.schoolYear;
    my_semester = global.behavior.semester;
    return gadget.getContract("ischool.AD.student").send({
      service: "_.GetAttendanceRecord",
      body: "<Request>\n  <StudentID>" + global.student.StudentID + "</StudentID>\n  <SchoolYear>" + global.behavior.schoolYear + "</SchoolYear>\n  <Semester>" + global.behavior.semester + "</Semester>\n</Request>",
      result: function(response, error, xhr) {
        var absences_d, absences_t, btn_active, items, tbody, thead, _absence, _period_type, _periods, _ref;
        btn_active = $('.my-schoolyear-semester-widget button.active');
        if (btn_active.attr("school-year") === my_schoolYear && btn_active.attr("semester") === my_semester) {
          resetAttendance();
          if (error != null) {
            return set_error_message('#mainMsg', 'GetAttendanceRecord', error);
          } else {
            absences_t = {};
            absences_d = [];
            if (((_ref = response.Result) != null ? _ref.Attendance : void 0) != null) {
              $(response.Result.Attendance).each(function() {
                var item;
                item = {};
                item['OccurDate'] = this.OccurDate;
                $(this.Detail.Attendance.Period).each(function() {
                  return item[this["@text"]] = this.AbsenceType;
                });
                return absences_d.push(item);
              });
            }
            items = [];
            _periods = global.periods;
            _absence = global.absence;
            _period_type = global.period_type;
            thead = "<th>日期</th>";
            $(_periods).each(function() {
              return thead += "<th>" + this.Name + "</th>";
            });
            thead = "<tr>" + thead + "</tr>";
            tbody = "";
            $(absences_d).each(function(i, item) {
              var isLeave, td;
              isLeave = false;
              td = '';
              $(_periods).each(function(j, period) {
                if (_absence[item[period.Name]]) {
                  isLeave = true;
                  td += "<td>" + (_absence[item[period.Name]] || '') + "</td>";
                  if (!absences_t[item[period.Name]]) {
                    absences_t[item[period.Name]] = {
                      total: 0
                    };
                  }
                  absences_t[item[period.Name]].total += 1;
                  if (!absences_t[item[period.Name]][period.Type]) {
                    absences_t[item[period.Name]][period.Type] = 0;
                  }
                  return absences_t[item[period.Name]][period.Type] += 1;
                } else {
                  return td += "<td></td>";
                }
              });
              if (isLeave) {
                return tbody += "<tr><td>" + item.OccurDate + "</td>" + td + "</tr>";
              }
            });
            $.each(absences_t, function(name, item) {
              items.push("<div class='thumbnail my-thumbnail-white rounded-lg py-3'>\n  <div class='caption my-subthumbnail-bottom font-semibold space-y-1'>\n    <div class='text-3xl text-primary'>" + (item.total || '') + "</div>\n<div class='text-base'>" + (name || '') + "</div>  </div>");
              items.push("<div class='px-3 py-1'><div class='border-t border-gray-100'></div></div><div class='flex flex-wrap gap-1'>");
              $.each(item, function(typename, value) {
                if (typename !== "total") {
                  return items.push("<div class='border-ll'></div><div class='text-gray-500 mx-auto'>" + typename + "：<span class='font-semibold'>" + value + "</span></div>");
                }
              });
              return items.push("</div></div>");
            });
            if (items.length === 0) {
              return $("#attendance-container").removeClass("hide").html("目前無資料");
            } else {
              $("#attendance-view").removeClass("hide");
              $("#attendance .my-thumbnails").html("<div class='thumbnails grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4'>\n  " + (items.join("")) + "\n</div>");
              return $("#attendance-container").addClass("hide").html(
                "<div class='overflow-x-auto mt-3'>"+
                "<table class='table table-striped table-bordered text-sm md:text-base min-w-full my-table'>"+
                "<thead>" + thead + "</thead><tbody class='text-gray-600'>" + tbody + "</tbody></table></div>"
                );
              // return $("#attendance-container").addClass("hide").html(
              //   "<div class='overflow-x-auto mt-3'>" +
              //     "<table class='min-w-full table-auto border border-gray-200'>" +
              //       "<thead class='bg-gray-100 text-sm text-gray-700'>" + thead + "</thead>" +
              //       "<tbody class='text-sm text-gray-600'>" + tbody + "</tbody>" +
              //     "</table>" +
              //   "</div>"
              // );
              
            }
          }
        }
      }
    });
  };

  getDiscipline = function() {
    var my_schoolYear, my_semester;
    my_schoolYear = global.behavior.schoolYear;
    my_semester = global.behavior.semester;

    // 先取得對照表
    return gadget.getContract("ischool.AD.student").send({
      service: "_.GetDisciplineNameMapping",
      body: "",
      result: function(mapping_response, mapping_error, mapping_xhr) {
        // 取得留校察看的對照文字
        var detentionText = "留校察看";  // 預設文字
        if (!mapping_error && mapping_response && mapping_response.name) {
          detentionText = mapping_response.name;
        }

        // 再取得獎懲紀錄
        return gadget.getContract("ischool.AD.student").send({
          service: "_.GetDisciplineRecord",
          body: `<Request>
            <StudentID>${global.student.StudentID}</StudentID>
            <SchoolYear>${global.behavior.schoolYear}</SchoolYear>
            <Semester>${global.behavior.semester}</Semester>
          </Request>`,
          result: function (response, error, xhr) {
            const btnActive = $('.my-schoolyear-semester-widget button.active');
        
            if (
              btnActive.attr("school-year") === global.behavior.schoolYear &&
              btnActive.attr("semester") === global.behavior.semester
            ) {
              resetDiscipline();
        
              if (error) {
                return set_error_message('#mainMsg', 'GetDisciplineRecord', error);
              }
        
              const items = [];
              const sumMerit = {
                ma: 0, mb: 0, mc: 0, // merits
                da: 0, db: 0, dc: 0, // demerits
                dd: 0                // detentions
              };
        
              const disciplines = response?.Result?.Discipline || [];
        
              disciplines.forEach((record) => {
                const occurDate = record.OccurDate?.substr(0, 10) || '';
                const reason = record.Reason || '';
                const detail = record.Detail?.Discipline;
        
                const buildBadge = (value, successClass, label) =>
                  `<td class="text-center whitespace-nowrap"><div class="${value !== 0 ? successClass : 'text-gray-300'}">${value}</div><div class='text-sm'>${label}</div></td>`;
        
                if (record.MeritFlag === "1") {
                  // Merits
                  const a = parseInt(detail?.Merit?.A || 0, 10) || 0;
                  const b = parseInt(detail?.Merit?.B || 0, 10) || 0;
                  const c = parseInt(detail?.Merit?.C || 0, 10) || 0;
                  sumMerit.ma += a;
                  sumMerit.mb += b;
                  sumMerit.mc += c;
        
                  items.push(`
                    <tr>
                      ${buildBadge(a, "text-cyan font-semibold", "大功")}
                      ${buildBadge(b, "text-cyan font-semibold", "小功")}
                      ${buildBadge(c, "text-cyan font-semibold", "嘉獎")}
                      <td class="lg:w-xl">
                        <div class='flex flex-col md:flex-row flex-wrap gap-x-2'>
                          <div>${occurDate}</div>
                          <div>${reason}</div>
                        </div>
                      </td>
                    </tr>
                  `);
                } else if (record.MeritFlag === "2") {
                  // Detention
                  sumMerit.dd++;
                  items.push(`
                    <tr style='height: 55px'>
                      <td colspan="3" class="my-detention">${detentionText}</td>
                      <td class="my-detention-text">
                        <div class='flex flex-col md:flex-row flex-wrap gap-x-2'>
                          <div>${occurDate}</div>
                          <div>${reason}</div>
                        </div>
                      </td>
                    </tr>
                  `);
                } else {
                  // Demerits
                  const a = parseInt(detail?.Demerit?.A || 0, 10) || 0;
                  const b = parseInt(detail?.Demerit?.B || 0, 10) || 0;
                  const c = parseInt(detail?.Demerit?.C || 0, 10) || 0;
                  const cleared = detail?.Demerit?.Cleared === '是';
                  const clearDate = detail?.Demerit?.ClearDate?.substr(0, 10) || '';
                  const clearReason = detail?.Demerit?.ClearReason || '';
        
                  if (!cleared) {
                    sumMerit.da += a;
                    sumMerit.db += b;
                    sumMerit.dc += c;
                  }
        
                  const badgeClass = (val, cleared) =>
                    val !== 0 ? "text-red font-semibold" : "text-gray-300";
        
                  items.push(`
                    <tr>
                      ${buildBadge(a, badgeClass(a, cleared), "大過")}
                      ${buildBadge(b, badgeClass(b, cleared), "小過")}
                      ${buildBadge(c, badgeClass(c, cleared), "警告")}
                      <td class='space-y-1'>
                        ${cleared ? `<div class='flex flex-col md:flex-row flex-wrap gap-x-2 my-offset'><div>${clearDate}</div><div>已銷過${clearReason}</div></div>` : ""}
                        <div class='flex flex-col md:flex-row flex-wrap gap-x-2'><div>${occurDate}</div><div>${reason}</div></div>
                      </td>
                    </tr>
                  `);
                }
              });
        
              // 更新畫面上方統計數字
              const updateBadge = (selector, value, cssClass) => {
                $(selector).html(`<span class='text-3xl ${value !== 0 ? cssClass : "text-gray-300"}'>${value}</span>`);
              };
        
              updateBadge("#merit-a", sumMerit.ma, "text-cyan");
              updateBadge("#merit-b", sumMerit.mb, "text-cyan");
              updateBadge("#merit-c", sumMerit.mc, "text-cyan");
              updateBadge("#demerit-a", sumMerit.da, "text-red");
              updateBadge("#demerit-b", sumMerit.db, "text-red");
              updateBadge("#demerit-c", sumMerit.dc, "text-red");
        
              if (sumMerit.dd > 0) {
                $("#demerit-d").html(`
                  <div class="thumbnail my-thumbnail-white rounded-lg p-1">
                    <div class="caption my-surveillance rounded-lg">
                      <div class='p-2'>${detentionText}</div>
                    </div>
                  </div>
                `);
              }
        
              // 表格或無資料提示
              if (items.length === 0) {
                $("#discipline-container").removeClass("hide").html("目前無資料");
              } else {
                $("#discipline-view").removeClass("hide");
                $("#discipline .my-thumbnails").removeClass("hide");
                $("#discipline-container").addClass("hide").html(`
                  <table class="table table-striped font-base mt-3">
                    <tbody>${items.join("")}</tbody>
                  </table>
                `);
              }
            }
          }
        });
        
      }
    });
  };

  set_error_message = function(select_str, serviceName, error) {
    var tmp_msg;
    tmp_msg = "<i class=\"icon-white icon-info-sign my-err-info\"></i><strong>呼叫服務失敗或網路異常，請稍候重試!</strong>(" + serviceName + ")";
    if (error !== null) {
      if (error.dsaError) {
        if (error.dsaError.status === "504") {
          switch (error.dsaError.message) {
            case "501":
              tmp_msg = "<strong>很抱歉，您無讀取資料權限！</strong>";
          }
        } else {
          if (error.dsaError.message) {
            tmp_msg = error.dsaError.message;
          }
        }
      } else if (error.loginError.message) {
        tmp_msg = error.loginError.message;
      } else {
        if (error.message) {
          tmp_msg = error.message;
        }
      }
      $(select_str).html("<div class='alert alert-error'>\n  <button class='close' data-dismiss='alert'>×</button>\n  " + tmp_msg + "\n</div>");
      return $(".my-err-info").click(function() {
        return alert("請拍下此圖，並與客服人員連絡，謝謝您。\n" + JSON.stringify(error, null, 2));
      });
    }
  };

  (function($) {
    return $.by = function(model, name, minor) {
      return function(o, p) {
        var a, b;
        if (o && p && typeof o === "object" && typeof p === "object") {
          a = o[name];
          b = p[name];
          if (a === b) {
            return (typeof minor === "function" ? minor(o, p) : 0);
          }
          if (typeof a === typeof b) {
            if (parseInt(a, 10) && parseInt(b, 10)) {
              a = parseInt(a, 10);
              b = parseInt(b, 10);
            }
            if (model === "desc") {
              return (a > b ? -1 : 1);
            } else {
              return (a < b ? -1 : 1);
            }
          }
          if (typeof a < typeof b) {
            return -1;
          } else {
            return 1;
          }
        } else {
          throw {
            name: "Error",
            message: "Expected an object when sorting by " + name
          };
        }
      };
    };
  })(jQuery);

}).call(this);
